#!/bin/bash

# Required: curl , jq, qdbus(qt)

#
# Upload an image:
# 	imgur /home/usename/Picture/ok.jpg
# Upload an image to imgur.com and output its new URL to clipboard
# Upload history stored in ~/.imgur_history

# API Key provided by ubuntuku@ovi.com
#apikey="1085e16a386ee42e786b72e6a7c51c0f9c96033e"

# function to output usage instructions
function usage {
	echo "Usage: $(basename $0) <filename>
Upload an image to imgur.com and output its new URL to clipboard and ~/.imgur_history" >&2
}
FILE="$HOME/.config/imgur/config"
if [ ! -f $FILE ] ; then
  mkdir -p $HOME/.config/imgur/
  echo '{"token":""}' > $HOME/.config/imgur/config
fi
token=$(jq -r '.token' $FILE)
# check arguments
if [ "$1" = "-h" -o "$1" = "--help" ] ; then
	usage
	exit 0
elif [ $# -ne 1 ]; then
	if [ $# == 0 ]; then
		kdialog --error "No file specified"
	else
		kdialog --error "Unexpected arguments"
	fi
	exit 16
elif [ ! -f "$1" ]; then
	kdialog --error "File \"$1\" not found"
	exit 1
elif [[ ${token} == "" ]]; then
  kdialog --error "Invali Token inside $FILE "
  exit 1
fi

# check curl is available
which curl >/dev/null 2>/dev/null || {
	kdialog --error "Couln't find curl, which is required."
	exit 17
}

# check jq is available
which jq >/dev/null 2>/dev/null || {
	kdialog --error "Couln't find jq, which is required for json parsing."
	exit 17
}
# check qdbus is available
which qdbus >/dev/null 2>/dev/null || {
	kdialog --error "Couln't find qdbus, which is required."
	exit 17
}

# upload the image
kdialog --passivepopup "imgur: Uploading image ..." 3
#response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$1" \
#	http://imgur.com/api/upload.xml 2>/dev/null)
# the "Expect: " header is to get around a problem when using this through the
# Squid proxy. Not sure if it's a Squid bug or what.

response=$(curl -H "Authorization:Bearer $token" -F "image=@$1" https://api.imgur.com/3/upload 2>/dev/null)
if [ $? -ne 0 ]; then
	kdialog --error "Upload failed"
	exit 2
elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
	err1=$(echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/')
	kdialog --error "$err1"
	exit 3
fi

# parse the response and output our stuff
#url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
url=$(echo $response | jq -r '.data.link')
#deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
deletehash=$(echo $response | jq -r '.data.deletehash')
deleteurl=$(echo "https://api.imgur.com/3/image/$deletehash")


qdbus org.kde.klipper /klipper org.kde.klipper.klipper.setClipboardContents "$url"

kdialog --passivepopup "Done. Image link copied to the clipboard" 5
echo >>$HOME/.imgur_history
echo "Source image: $1" >>$HOME/.imgur_history
echo "-------------" >>$HOME/.imgur_history
echo "Direct Link: $url" >>$HOME/.imgur_history
echo "Deletion Link: $deleteurl" >>$HOME/.imgur_history
